---
apiVersion: v1
kind: Service
metadata:
  name: chibisafe-backend
  namespace: chibisafe
  labels:
    app: chibisafe
spec:
  selector:
    app: chibisafe-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: chibisafe
  namespace: chibisafe
spec:
  selector:
    app: chibisafe
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-chibisafe
  namespace: chibisafe
spec:
  selector:
    app: nginx
  ports:
  - name: http
    targetPort: 80
    port: 80
  type: LoadBalancer