apiVersion: apps/v1
kind: Deployment
metadata:
  name: chibi-safe-proxy
  labels:
    app: chibi-safe-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chibi-safe-proxy
  template:
    metadata:
      labels:
        app: chibi-safe-proxy
    spec:
      containers:
        - name: chibi-safe-proxy
          image: wololoaeyoyo/chibiproxy:latest
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: BACKEND_TARGET
              value: http://chibisafe-backend.chibisafe.svc.cluster.local:8000
            - name: FRONTEND_TARGET
              value: http://chibisafe.chibisafe.svc.cluster.local:8001
            - name: PORT
              value: "3001"
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_ENV
              value: "production"
      restartPolicy: Always