---
apiVersion: v1
kind: Service
metadata:
  name: chibisafe-backend
  labels:
    app: chibisafe
spec:
  selector:
    app: chibisafe
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP