apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: alloy
spec:
  targetNamespace: alloy 
  chart:
    spec:
      chart: k8s-monitoring
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 3.7.1

  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: k8s-monitoring-configmap
      valuesKey: values.yaml