apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: alloy
spec:
  targetNamespace: alloy
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: "4.1.*"
  interval: 5m0s
  valuesFrom:
    - kind: ConfigMap
      name: k8s-monitoring-configmap
      valuesKey: values.yaml








      
