apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-monitoring-configmap
  namespace: alloy
data:
  values.yaml: |
    cluster:
      name: default

    destinations:
      loki:
        type: loki
        url: http://loki-loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      mimir:
        type: prometheus
        url: http://mimir-mimir-gateway.mimir.svc.cluster.local/api/v1/push

    collectors:
      alloy-logs:
        enabled: true
        alloy:
          clustering:
            enabled: true
      alloy-metrics:
        enabled: true
        alloy:
          clustering:
            enabled: true

    podLogsViaKubernetesApi:
      enabled: true
      collector: alloy-logs

    clusterEvents:
      enabled: true
      collector: alloy-logs

    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true
      linux-host-metrics:
        deploy: true

    nodeMetrics:
      enabled: true
      collector: alloy-metrics
      destinations:
        - mimir
      metricsTuning:
        includeMetrics:
          - node_boot_time_seconds

    clusterMetrics:
      enabled: true
      collector: alloy-metrics
      destinations:
        - mimir
      kube-state-metrics:
        metricsTuning:
          includeMetrics:
            - kube_namespace_created
      cadvisor:
        metricsTuning:
          includeMetrics:
            - machine_cpu_cores

    podLogs:
      enabled: false

    hostMetrics:
      enabled: true
      collector: alloy-metrics
      destinations:
        - mimir
      linuxHosts:
        enabled: true
        metricsTuning:
          includeMetrics:
            - node_uname_info
