apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-monitoring-configmap
  namespace: alloy
data:
  values.yaml: |
    cluster:
      name: default

    destinations:
      loki:
        type: loki
        url: http://loki-loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      mimir:
        type: prometheus
        url: http://mimir-mimir-gateway.mimir.svc.cluster.local/api/v1/push

    collectors:
      alloy-logs:
        enabled: true
        alloy:
          clustering:
            enabled: true
      alloy-metrics:
        enabled: true
        alloy:
          clustering:
            enabled: true

    podLogsViaKubernetesApi:
      enabled: true
      collector: alloy-logs

    clusterEvents:
      enabled: true
      collector: alloy-logs

    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true
      linux-host-metrics:
        deploy: true

    nodeMetrics:
      enabled: true
      collector: alloy-metrics
      destinations:
        - mimir

    clusterMetrics:
      enabled: true
      collector: alloy-metrics
      destinations:
        - mimir
      kube-state-metrics:
        metricsTuning:
          includeMetrics:
            - kube_namespace_created
      cadvisor:
        metricsTuning:
          includeMetrics:
            - machine_cpu_cores
      kubeDNS:
        enabled: true
        metricsTuning:
          includeMetrics:
            - coredns_build_info
            - coredns_cache_evictions_total
            - coredns_cache_hits_total
            - coredns_cache_misses_total
            - coredns_cache_size
            - coredns_dns_request_duration_seconds
            - coredns_dns_request_size_bytes
            - coredns_dns_requests_total
            - coredns_dns_response_size_bytes
            - coredns_dns_responses_total
            - coredns_forward_healthcheck_broken_total
            - coredns_forward_healthcheck_failures_total
            - coredns_forward_request_duration_seconds
            - coredns_forward_requests_total
            - coredns_forward_responses_total
            - coredns_health_request_duration_seconds
            - coredns_health_request_failures_total
            - coredns_kubernetes_dns_programming_duration_seconds
            - coredns_panics_total
            - coredns_plugin_enabled
      apiServer:
        enabled: true
        metricsTuning:
          includeMetrics:
            - apiserver_request_total
            - apiserver_request_duration_seconds
            - apiserver_current_inflight_requests
            - apiserver_dropped_requests_total
            - apiserver_request_terminations_total
            - apiserver_requested_deprecated_apis
            - apiserver_request_duration_seconds_sum
            - apiserver_request_duration_seconds_count
            - workqueue_depth
            - process_resident_memory_bytes
            - process_cpu_seconds_total

    podLogs:
      enabled: false

    hostMetrics:
      enabled: true
      collector: alloy-metrics
      destinations:
        - mimir
      linuxHosts:
        enabled: true
        metricsTuning:
          includeMetrics:
            - node_uname_info
            - node_boot_time_seconds
            - node_time_seconds
            - node_load1
            - node_load5
            - node_load15
            - node_disk_io_now
            - node_disk_read_bytes_total
            - node_disk_writes_completed_total
            - node_disk_write_bytes_total
            - node_network_receive_bytes_total
            - node_network_transmit_bytes_total
            - node_network_receive_packets_total
            - node_network_transmit_packets_total
            - node_network_receive_errs_total
            - node_network_transmit_errs_total
            - node_network_receive_drop_total
            - node_network_transmit_drop_total
