apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  targetNamespace: loki 
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 6.49.0

  interval: 1m0s
  values:
    containerEnvVars:
      ACCESS_KEY: 
        valueFrom:
          secretKeyRef:
            name: loki-secret
            key: ACCESS_KEY
      SECRET_KEY: 
        valueFrom:
          secretKeyRef:
            name: loki-secret
            key: SECRET_KEY
  valuesFrom:
    - kind: ConfigMap
      name: loki-configmap