apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  targetNamespace: loki 
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 6.49.0

  interval: 1m0s
  timeout: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: loki-configmap
      valuesKey: values.yaml
  values:
    loki:
    storage:
      extraEnv:
      - name: ACCESS_KEY 
        valueFrom:
          secretKeyRef:
            name: loki-s3-secret
            key: ACCESS_KEY
      - name: SECRET_KEY 
        valueFrom:
          secretKeyRef:
            name: loki-s3-secret
            key: SECRET_KEY