apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  targetNamespace: loki 
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 6.49.0

  interval: 1m0s
  values:
    tempo:
      extraArgs:
        config.expand-env: true
      extraEnvFrom:
        - secretRef:
            name: loki-secret
  valuesFrom:
    - kind: ConfigMap
      name: loki-configmap
      valuesKey: values.yaml