apiVersion: grafana.integreatly.org/v1beta1  
kind: GrafanaDatasource
metadata:
  name: github-datasource
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  valuesFrom:
    - targetPath: secureJsonData.accessToken
      valueFrom:
        secretKeyRef:
          name: github-datasource-secret
          key: GITHUB_TOKEN
  datasource:
    name: GitHub
    type: grafana-github-datasource
    access: proxy
    isDefault: false
    url: https://api.github.com
    secureJsonData:  
      "accessToken": "${GITHUB_TOKEN}"