---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: default
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - env:
            - name: OWNER
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: OWNER
            - name: PREFIX
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: PREFIX
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: token-discord
          image: harshraj9812/hr-bot-jmusicbot:0.3.9
          name: discord-hr-music-bot
      restartPolicy: Always
