apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-discordbot-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard   # Uncomment and set to match your cluster's StorageClass
