apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-web
  namespace: personal-web-site
  labels:
    app: resume-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-web
  template:
    metadata:
      labels:
        app: resume-web
    spec:
      containers:
        - name: resume-web
          image: wololo-aeyoyo/humberto-resume:master
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
