apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f .\chibisafe.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert -f .\chibisafe.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: caddy
    spec:
      containers:
        - env:
            - name: BASE_URL
              value: '":80"'
          image: caddy:2-alpine
          name: caddy
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-claim0
              readOnly: true
            - mountPath: /app/uploads
              name: caddy-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: caddy-claim0
          persistentVolumeClaim:
            claimName: caddy-claim0
            readOnly: true
        - name: caddy-claim1
          persistentVolumeClaim:
            claimName: caddy-claim1
            readOnly: true
