apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: chibisafe-server-claim0
  name: chibisafe-server-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
