apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f .\chibisafe.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: chibisafe-server
  name: chibisafe-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chibisafe-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert -f .\chibisafe.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: chibisafe-server
    spec:
      containers:
        - env:
            - name: ADMIN_PASSWORD
              value: admin
          image: chibisafe/chibisafe-server:dev
          name: chibisafe-server
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/database
              name: chibisafe-server-claim0
            - mountPath: /app/uploads
              name: chibisafe-server-claim1
            - mountPath: /app/logs
              name: chibisafe-server-claim2
      restartPolicy: Always
      volumes:
        - name: chibisafe-server-claim0
          persistentVolumeClaim:
            claimName: chibisafe-server-claim0
        - name: chibisafe-server-claim1
          persistentVolumeClaim:
            claimName: chibisafe-server-claim1
        - name: chibisafe-server-claim2
          persistentVolumeClaim:
            claimName: chibisafe-server-claim2
