apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secret
  namespace: umami-web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: umami-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: n8n-secret/data/postgres
        property: data.username
    - secretKey: password
      remoteRef: 
        key: n8n-secret/data/postgres
        property: data.password