apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo-release
  namespace: tempo
spec:
  targetNamespace: tempo 
  chart:
    spec:
      chart: tempo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 1.24.1

  interval: 1m0s
  values:
    tempo:
      extraArgs:
        config.expand-env: true
      extraEnvFrom:
        - secretRef:
            name: tempo-s3-secret
  valuesFrom:
    - kind: ConfigMap
      name: tempo-configmap
      valuesKey: values.yaml