apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo-release
  namespace: tempo
spec:
  targetNamespace: tempo 
  chart:
    spec:
      chart: tempo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 1.24.1

  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: tempo-secret
