apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-secret
  namespace: mimir
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: mimir-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          # name of the configmap to pull in
          name: mimir-configmap
          # here you define the keys that should be used as template
          items:
          - key: values.yaml
            templateAs: Values
  data:
    - secretKey: ACCESS_KEY
      remoteRef:
        key: lgtm/data/mimir
        property: data.ACCESS_KEY
    - secretKey: SECRET_KEY
      remoteRef: 
        key: lgtm/data/mimir
        property: data.SECRET_KEY




