apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alloy-collector-secret
  namespace: alloy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: alloy-collector-secret
    creationPolicy: Owner
  data:
    - secretKey: FARO_API_KEY
      remoteRef:
        key: alloy-collector/data/secrets
        property: data.FARO_API_KEY
