apiVersion: v1
kind: Service
metadata:
  name: alloy-collector
  namespace: alloy
spec:
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy-alloy-collector
  type: ClusterIP
  ports:
    - name: faro
      port: 12347
      targetPort: 12347
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
