apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-collector-configmap
  namespace: alloy
data:
  values.yaml: |
    controller:
      type: deployment
    alloy:
      listenAddr: 0.0.0.0
      listenPort: 12345
      extraArgs:
        - --log.level=debug
      extraEnv:
        - name: FARO_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-collector-secret
              key: FARO_API_KEY
      configMap:
        create: true
        name: alloy-collector-configmap
        content: |-
          faro.receiver "frontend" {
            server {
              listen_address       = "0.0.0.0"
              listen_port          = 12347
              cors_allowed_origins = ["*"]
              api_key              = sys.env("FARO_API_KEY")
            }

            output {
              logs   = [loki.write.faro.receiver]
              traces = [otelcol.exporter.otlp.tempo.input]
            }
          }

          loki.write "faro" {
            endpoint {
              url = "http://loki-loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
            }
          }

          otelcol.exporter.otlp "tempo" {
            client {
              endpoint = "tempo-tempo-release.tempo.svc.cluster.local:4317"
              tls {
                insecure = true
              }
            }
          }

          otelcol.receiver.otlp "otlp_ingest" {
            grpc {
              endpoint = "0.0.0.0:4317"
            }
            http {
              endpoint = "0.0.0.0:4318"
            }

            output {
              metrics = [otelcol.processor.batch.otlp_ingest.input]
              logs    = [otelcol.processor.batch.otlp_ingest.input]
              traces  = [otelcol.processor.batch.otlp_ingest.input]
            }
          }

          otelcol.processor.batch "otlp_ingest" {
            output {
              metrics = [otelcol.exporter.prometheus.otlp_ingest.input]
              logs    = [otelcol.exporter.loki.otlp_ingest.input]
              traces  = [otelcol.exporter.otlphttp.tempo_otlp.input]
            }
          }

          otelcol.exporter.otlphttp "tempo_otlp" {
            client {
              endpoint = "http://tempo-tempo-release.tempo.svc.cluster.local:4318"
              tls {
                insecure = true
              }
            }
          }

          otelcol.exporter.prometheus "otlp_ingest" {
            forward_to = [prometheus.remote_write.mimir.receiver]
          }

          otelcol.exporter.loki "otlp_ingest" {
            forward_to = [loki.write.faro.receiver]
          }

          prometheus.exporter.self "alloy_collector" { }

          prometheus.scrape "alloy_collector" {
            scrape_interval = "60s"
            targets    = prometheus.exporter.self.alloy_collector.targets
            forward_to = [prometheus.remote_write.mimir.receiver]
          }

          prometheus.remote_write "mimir" {
            endpoint {
              url = "http://mimir-mimir-gateway.mimir.svc.cluster.local/api/v1/push"
            }
          }
