apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: pepaless-binding
  namespace: personal-web-site
subjects:
- name: pepaless-service
  spec:
    fqdn: pepaless.merwebo.org
    target: http://pepaless-service.personal-web-site.svc:3000
tunnelRef:
  kind: ClusterTunnel
  name: tunnel-cluster-mer
