apiVersion: v1
kind: Service
metadata:
  name: pepaless-service
  namespace: personal-web-site
  labels:
    app: pepaless
spec:
  type: ClusterIP
  selector:
    app: pepaless
  ports:
    - name: http
      port: 80
      targetPort: 80
