apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepaless
  namespace: personal-web-site
  labels:
    app: pepaless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pepaless
  template:
    metadata:
      labels:
        app: pepaless
    spec:
      containers:
        - name: pepaless
          image: wololoaeyoyo/meme-react
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
