apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: gotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotify
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: gotify/server:latest
          imagePullPolicy: Always
          env:
            - name: GOTIFY_URLS
              value: "https://gotify.wololoaeyoyo.com"
            - name: ENABLE_CONSOLE_LOG
              value: "true"
            - name: ENABLE_SCALAR_UI
              value: "true"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /app/data
              name: gotify-data
      volumes:
        - name: gotify-data
          persistentVolumeClaim:
            claimName: gotify-data
