apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: WEBPASSWORD
      remoteRef:
        key: pihole/data/secrets
        property: data.WEBPASSWORD
