---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-release
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: 0.17.0
  interval: 1m0s
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v0.19.2
      pullPolicy: IfNotPresent
