apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespaces
  - namespaces/alloy-namespace.yaml
  - namespaces/chibi-safe-namespace.yaml
  - namespaces/cloudflare-tunnel-ingress-controller-namespace.yaml
  - namespaces/external-secrets-namespace.yaml
  - namespaces/grafana-namespace.yaml
  - namespaces/kubernetes-dashboard-namespace.yaml
  - namespaces/loki-namespace.yaml
  - namespaces/longhorn-namespace.yaml
  - namespaces/metallb-namespace.yaml
  - namespaces/minecraft-namespace.yaml
  - namespaces/mimir-namespace.yaml
  - namespaces/n8n-namespace.yaml
  - namespaces/openclaw-operator.yaml
  - namespaces/pyroscope-namespace.yaml
  - namespaces/reloader-snamespace.yaml
  - namespaces/tempo-namespace.yaml
  - namespaces/traefik-namespace.yaml
  - namespaces/vault-namespace.yaml
  
  # Helm Repositories
  - helmrepositories/cloudflare-tunnel-ingress-controller-repo.yaml
  - helmrepositories/external-secrets-repo.yaml
  - helmrepositories/grafana-helm.yml
  - helmrepositories/longhorn-repo.yaml
  - helmrepositories/minecraft-repo.yaml
  - helmrepositories/openclaw-operator.yaml
  - helmrepositories/reloader-repo.yaml
  - helmrepositories/vault-repo.yaml
  
  # Kustomizations
  - kustomization/chibi-safe-kustomization.yaml
  - kustomization/cloudflare-tunnel-ingress-controller-kustomization.yaml
  - kustomization/discord-bot-kustomization.yaml
  - kustomization/external-secrets-kustomization.yaml
  - kustomization/lgtm-kustomization.yaml
  - kustomization/longhorn-kustomization.yaml
  - kustomization/metalb-kustomization.yaml
  - kustomization/minecraft-kustomization.yaml
  - kustomization/n8n-kustomization.yaml
  - kustomization/nginx-kustomization.yaml
  - kustomization/openclaw-operator-kustomization.yaml
  - kustomization/openclaw-kustomization.yaml
  - kustomization/vault-kustomization.yaml
