---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-kubernetes
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-kubernetes
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-kubernetes
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/wololo-aeyoyo/cluster-kubernetes
  ref:
    branch: main
