apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: tunnel-cluster-mer
  namespace: tunnel-cluster-mer
spec:
  cloudflare:
    accountId: "85dfa5d3c083a5bc0b569603e781206c"
    domain: "merwebo.org"
    secret: cloudflare-api
    accountName: "Humberto.raniolo@gmail.com's Account"
  newTunnel:
    name: "tunnel-cluster-mer"
  size: 2
