apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:0tNQNNi+lnEHemFwQc542q9RfPaPtyL+KFFEKtPEIHFBKbV6e4kDkw==,iv:AZq+GQP3EYUqvaPIvWxWFgmbzpyeUNPQSG/uzGO7vjA=,tag:Z0Agj86dIItfCmvWHNstBQ==,type:str]
    cloudflare-account-id: ENC[AES256_GCM,data:fKbaQ4u0wAqKDEutEs9Hkdey6XkLQ57qJHkz/tkT0sc=,iv:pU20Yr2FLIEq7jSo1ydbz7AJSpD3/qZXUlYs2tFP2Ms=,tag:ASS09NIxaGS6FFjxf2NWfQ==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:9l9LwSrMHjU4,iv:zL6RbUiFSPBBO91YsRszXub+B+6IYK0UckC235j8GOQ=,tag:9F/VtWb6r3H4V2Dl2o0SYA==,type:str]
sops:
    lastmodified: "2026-05-02T03:58:41Z"
    mac: ENC[AES256_GCM,data:Cm8OGGm5wVdTRC7dpKcEtMezomL02aX+2Up1Xm3QGV7nwEBXMWZbOTVek297YVpVn/BqXrJB8zIy8o1u0wfR9i/j8xbDfK/esH5uMYNBa3uHfYSFzjZXwIDccuKZldiaeO5CywQHOQA/+VPNIq9vnNwJg8sZ0nAc/8NPr4DCbfY=,iv:wkN/pCkQy3fQeJqRe+Qb8K6CbBTC/5X0Ap2mP+V6L7g=,tag:1S8bD/VNjjRTSR5Wt1xeEw==,type:str]
    pgp:
        - created_at: "2026-05-02T03:58:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQwAidZ7ljxlPjYMK+Mtm5mhT1I0yDOpq3qA3kFZJlnUKi66
            W27ipvbQr8djHr0WyBjhe2eFuekSZz5r5dxqfkD6KR3Q2Tn8J4dhebT7vopaoLbC
            5tmXcV2Lc4W/ff68GA5/MCSoKkqrYwizVMgMx0TLLfdAfGxenfw9I/F5nAQaAKyQ
            JDd4bbb2iTCFRWWcunUwEsrSwaijfisVoD4reAyHdNGuVH2cZErEoP0ksWjyO78P
            ipACadqIx3xu0PpbV35VAGwqSg92bGmzRPfdsVHH1LvicbyBZh5i0wvueNosWFWd
            Q4O1dn6BxxeWRyn1L0swm189jneSntEClHJYUA3/2Q37Rdtlc8xm66LO8GWdZyag
            LoAhGBvjJdAnSthBaktUfuBvs+NjutqsoJAMDLu7zvEIi9ots5fvqksDprfpmHJB
            GopDaue984FfhmQ1U71TkFSaI35TdOlA/BIdpj69fc74YVLF+vyjnIor+WdkuV4j
            3DM7v6ohKETJLbVytDf70l4Bz46IC6ywpgm7WkAn0P3mF3IoSDvqBh1nDIa61miI
            DNKq1PFMJxrbfWgdnZMXAN+Sr2pqI8uNDlaprL9Y3udph8MmT/DWuUG2Xg7YTOkE
            ZgfVm9sEpzqr2vedUE7R
            =7ulD
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
