apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: tunnel-cluster-mer
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:DzeDoftrUADWMyho+82tSIZvu6qe3NvhJSgpioqQwgS7Z8spnit5Gw==,iv:fjhAj+qtG7AU0R31rrBQYcRbIrMFNsMQxhB4BWEwYwo=,tag:lX7+o6RGLI283L2Ip1RW5w==,type:str]
    cloudflare-account-id: ENC[AES256_GCM,data:h9dx2BorhLj2TZQHvNwPl+1+skCNLGx86FOsSCg1sE0=,iv:TPKWV70Ci7P+s6ATjwklBVggbluRvvXj3o3Zt/xqbeA=,tag:iCe+vYjh9Scqyueo3qP14w==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:Ema7JyTcT7gJ,iv:RMv+eif7hRqxfNei1wzaWDvByZgDXbgG74xZ/npwCAk=,tag:nFOWP3fTX6IOObjUP39c2A==,type:str]
sops:
    lastmodified: "2026-04-30T04:14:51Z"
    mac: ENC[AES256_GCM,data:cU5DQpRaTPR191ZrAXqY5zm4PolRF7MwA9dL8BE63u6eSLMPguKvvx5IuEDjaKHYqW4MpeUuGp8NP17+wfYqnSHEE5eyGNSdfAY7G8LKMQBZl1P4HTaMFfhfya+LXIMWK8sH1sc8aPJvu/OyrXQoNWm6rMGePo377nrMUu7x7Jc=,iv:EL20vv5V+RviMNexzCv0IygL27bq8qorRBbyH6xcIZU=,tag:fTcA2rOPbxQeVd1tZ68PEw==,type:str]
    pgp:
        - created_at: "2026-04-30T04:14:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQv/TYHBWarpDhnnmW7MF5os+At+cVk/1W7Gt5VMp9hktsji
            SdGZimmUYzp64sP+7/S3yXnkt0oLsfzDYt3rgFxPqzfFiccC1X9Vvw6wNdmORV7R
            4NvUTdi1CW8YnOOgBl4kVXOSWPt2S4TyS/IYazgiP29Lo410mNoN1XDYqt/Zxhjl
            1dgah9Os0La//3H0zYpruCfQB5txIvoW5A/FgcUU9MvaZqjnj+bub405y5lAfm7X
            C0FwEkbtKCcGhWxPQS/M72MRrmHGr/GcrQ7LB6kniXQjGzhHBtGVfcejdRovYDAR
            XR+42HjjWtzmJX+5UhnVwT4O/MZKG5QsX62nzkJ4rT8/IAwuITGKD/mepCVonnf3
            M5M2x/X7X1kRvhi4Rx+6Z4POdxYb8bRbw2ft6st2QRLu3dJNKexqWpfWQEZPYRJE
            s0CHhZpqH5gi5sFfKmleYdlOYULenW0kGRLFsYMge7XhwhHiq2o4wQcFZ+7ct5dk
            WvGHsYL5NT5lX0E1GThF0l4B2woUhwwm8WcL1fUYi6lAJiFNMM7iL49+efR3a54+
            SjzAnxSC0bnMVXnFvHA3vFPTZqX1QQZaahCFUk/lL8tN69Rrdkepe9LfCphx9W9W
            wDAa4jkh5fwu/nCUaj18
            =zyHD
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
