apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: cloudflare-tunnel-ingress-controller
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:F7C1ureSZW1vmgHjF8ZpQ10597aF1ZKmUhMfO613xxLgXa6kTs9z0w==,iv:QrbM7l04zvzXMJNvt+3jfVRAF0TYu/NDs9utylECYLc=,tag:oQiZ9FafHG3m+ony3rsVfw==,type:str]
    cloudflare-account-id: ENC[AES256_GCM,data:zw3T6MHuaafrzI8I+fUv1A3+SkOQYPhy7SV1gwDB+FA=,iv:FK5/KrpKDddoh3tWggx5WsLvgLCg7Hl0sZvHmXN93JM=,tag:6Bor53R2lTwsrIrj0Xkh6A==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:Epwqum19W26n,iv:h5Nte31RiO3aHYaoLHbMRkITN7yxHOR/tMXAGXCZK44=,tag:Fi2gVg7aVU28tCcKY5Bhvw==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:qzuquvYxbE7eMXy5yhjs2muAkORGTm2cspMnYPHli2TqMxxBz+HNx8F6YC1qyPUvPaFYplKMYjVYrvHjR9s4HDq572QUG3IjZyaDbHrD+YCIChb32JgDmL7RtSMd/v6NvaHMcPfjo13H5fCfTqVDz7jtmPU0cg36rjCnFRVv4yhJcjVexkowT8Q676APNDRmw0Q8Z5e06SZpDsSC5uZDhWS3LVOLaaUhHzvbmT3KxqTQVgiAby5cag==,iv:Hpj1sQnpj3weojxuA4VujCg8tfJbaBe5T8I1HfMGG44=,tag:UO8WrMbiuRiSxTIPntgPOA==,type:str]
sops:
    lastmodified: "2026-05-01T05:03:44Z"
    mac: ENC[AES256_GCM,data:FSlmRqc0i3gO2jHXRrKz36gJ/i8lHQJ5eiAv7yusuICdeJxdayNkN5K7w+jiDEpFTWhA60/q8QiXbJLfSQBEcmGyEIEzYhxJNiJ3zIaKVh0YGlayKKqFxQup+6WRqAYF5qdPa/yFlOLxFRmLUYJYIua82CobD5HznvXoPR4SKK0=,iv:HI7BU5S9BuXjphTHr+3Wfqdg8fXv/KQjO3bAsWw7qS0=,tag:5+GOaIQWZsmA7Dh8YcYvBQ==,type:str]
    pgp:
        - created_at: "2026-05-01T05:03:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQv+MQdLcx3bAmxcJOFcXg/RiG58PYPvd5ECZg+NKFcNzpwV
            4F1WauDspNZOHUZG2Vk5seTeDFqwKclZ8rLnheuOgNlNj1TZh4uKaSPTMGC13cig
            +iBzs9Twt3XwwS5fPPnNpYW+/o71IWunXpouWLAdHwtKAFgz5QzsZZCMSYxGztZS
            guG3gNS81WMFSu6DpkDt61HYNo9sxUgvNOmGfYlIqbmzHP3j4sEjLpXbFmJFXnFW
            RUfyN+qB4cCU1cqzxIBYqf8RCIdR4uZC5KGuKpd6NnqpoS3BSnGWgXvWBtQkVNSP
            S/TioZJwjQyR/ZVXj+W3sUeDgZEMp4GbXkSKVrsW6t8PLs1j04GsiDqDmEjV+e0x
            RVH0bHlGys49uaBYyVXbPwvEixHgtfV6znlhghg8l9OhMNRIsNgWrjPBBEDCgJN5
            EGROJCn6EBwZr5yK4mFTwMYw9ZlMzEl12CUGyJqDcfkvAyrRkSAtIZBpPq1nlcdx
            4aD1fwn5CyjV49cf/lOU0l4BrL5MNtVQSSTEtva0sL//1FK65Ns2Luhul8xoEBB8
            bI4Zu4TGODg+EjHPifg9oaQy3GnSHZDPxeDA4+qKNXq9JEBly0F0BOH6OgLcdzp1
            dBw04DkpiD2Dum+Gxx//
            =7acj
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
