apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-faro
  namespace: alloy
spec:
  targetNamespace: alloy
  chart:
    spec:
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 1.5.1
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: alloy-faro-configmap
      valuesKey: values.yaml
