apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: cloudflare-tunnel-ingress-controller
spec:
  interval: 1h0m0s
  url: https://helm.strrl.dev