---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-release
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vault
        version: 0.30.1
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: vault-configmap