apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-secret
  namespace: telegram-bot
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: telegram-bot-secret
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.TELEGRAM_BOT_TOKEN
    - secretKey: TELEGRAM_ALLOWED_USER_IDS
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.TELEGRAM_ALLOWED_USER_IDS
    - secretKey: TELEGRAM_ALLOWED_CHAT_IDS
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.TELEGRAM_ALLOWED_CHAT_IDS
    - secretKey: LLM_API_KEY
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.LLM_API_KEY
    - secretKey: YTDLP_USERNAME
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.YTDLP_USERNAME
    - secretKey: YTDLP_PASSWORD
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.YTDLP_PASSWORD
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.SPOTIFY_CLIENT_ID
    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.SPOTIFY_CLIENT_SECRET
    - secretKey: SPOTIFY_REFRESH_TOKEN
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.SPOTIFY_REFRESH_TOKEN
    - secretKey: SPOTIFY_DEFAULT_PLAYLIST_ID
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.SPOTIFY_DEFAULT_PLAYLIST_ID
    - secretKey: GELBOORU_API_KEY
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.GELBOORU_API_KEY
    - secretKey: GELBOORU_USER_ID
      remoteRef:
        key: telegram-bot/data/secrets
        property: data.GELBOORU_USER_ID
