apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yt-dlp-secret
  namespace: yt-dlp-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: yt-dlp-secret
    creationPolicy: Owner
  data:
    - secretKey: CHIBISAFE_API_KEY
      remoteRef:
        key: yt-dlp-backend/data/secrets
        property: data.CHIBISAFE_API_KEY
    - secretKey: PG_PASSWORD
      remoteRef:
        key: yt-dlp-backend/data/secrets
        property: data.PG_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: yt-dlp-backend/data/secrets
        property: data.JWT_SECRET
    - secretKey: PG_USER
      remoteRef:
        key: yt-dlp-backend/data/secrets
        property: data.PG_USER
    - secretKey: PG_DATABASE
      remoteRef:
        key: yt-dlp-backend/data/secrets
        property: data.PG_DATABASE
