apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secret
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: tailscale-secret
    creationPolicy: Owner
    template:
      data:
        values.yaml: |
          oauth:
            clientId: "{{ .clientID }}"
            clientSecret: "{{ .clientSecret }}"
  dataFrom:
    - extract:
        key: tailscale/data/secrets





