apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secret
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: tailscale-secret
    creationPolicy: Owner
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: tailscale/data/secrets
        property: data.client_id
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: tailscale/data/secrets
        property: data.client_secret





