---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: kube-apiserver
  namespace: tailscale
spec:
  type: kube-apiserver
  replicas: 2
  kubeAPIServer:
    hostname: k8s-api
    mode: auth
