---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale-repo
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1h0m0s
  targetNamespace: tailscale
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: tailscale-secret
            key: CLIENT_ID
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: tailscale-secret
            key: CLIENT_SECRET
