apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cloudflare-tunnel-ingress-controller
data:
    cloudflaresecret: ENC[AES256_GCM,data:cNtgsNPCfHdJMyCJYnvSerjupx2XHx1dQ+GKgNWh4Nvhe+HZu3FLKw==,iv:uEMkzUZBwDJlLTnpudTB0Us54LQ33PF49NlgTckyGHk=,tag:VvpSJjqLnChmDfBmYybK6A==,type:str]
    cloudflareaccount: ENC[AES256_GCM,data:qFFvBkRtlywff5Is0u5svUgOhtng9a2yht4ls6CYNek=,iv:jLhqO2K9dIsKgrNbYqyeVEApc2L7BBHaBr5tTpcEWvY=,tag:B2E/BD4emWg53Vd+QVatCg==,type:str]
sops:
    lastmodified: "2026-03-15T21:51:50Z"
    mac: ENC[AES256_GCM,data:hj1n2bEE8dkvWBmiEbTuimQ2UnwaK4Xg9XYPR1ZYRAH5vn3B7rVVQrJsn3E5r9CHDALHBl0BwFHQ/34s3vL9qrFQGGP3Ai+6gGMZQns9yTBABwGXNamMYp4/wyZHRCNdAQRBC+4gnPRhFgpxY0te8GepFrJonvVWearfLeF/SfE=,iv:YiXZCAIMYEtNd1XEV3AWUmKkdgZL0gsM2SF1yC5xlBQ=,tag:OcuGOAXXuXIVx5VkugewyA==,type:str]
    pgp:
        - created_at: "2026-03-15T21:51:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQv/SnTZZ0IuiqtycgNVd2uHmSEsxT5MTkKIiUEO44NmCgZW
            b+KE1fWsUAXqYn4A8AINZRrxj74672Q7TcFDCmYSL71C8IpmSNa1B46vMrPoQnby
            193yRZEr9g0XuA/U/XFQ/93a44hzUR/SZPCAbo2MwyC/MxKp/VENthhysgBumkMj
            Mv2gEfSPgPbYRpyvXxtBiM6fHvQxAQHRexgCebacI9gr4IjtIP4qVYyORv9uAVrH
            BQ9Buok6hKnbRJ74O2TFPcU/83Rkz+SvHndJf4ACjiQrmBXxl7CQsQWlMyovQ/Ue
            lW+wUIx+oYLu1m2JWkfYzIOUjrJyLyeEeM7h810In4YWS4WZH3KiyYkfo4LVOPOg
            8s+M3UY8AlayYDFfF4H7eR2g4BBDoWJFQcQqgtXjM55Y7iVABI1cUCGITZ1vXhL1
            iGYortMS/R5TljYtiQGBgXvzWrwJ/j3n09EOEdJSJ/srU6+qU2lLMhaTbEeEUoM5
            JJOuwyiWp8h4vpFTUTiB0l4B+sSOfgS03qKlsIpa8eoLgGmql13sS3h8C4Dab8fO
            AYJXLoFXIn2z+QAaNnYzqR3jcDhnlVC05LTqM1hea81ysrc7aWr3F3W/UsblEuWh
            i2uZGHI0Zlrwth8LAZ+e
            =tx9M
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
