apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: cloudflare-tunnel-ingress-controller
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:YiFXz3y9DL5r+lyi7x9/A3DAgSiRPZ2rnjumTrfNudgxuMGyCbvO+w==,iv:F2nyq6INFB1lBP03F7r3L/IEC6obbm2wv7c9bGiQjbs=,tag:glYKmC7DgivLRRQ/4EzR8A==,type:str]
    cloudflare-account-id: ENC[AES256_GCM,data:hWPMzM2VX9Pq+/vr6+aazg21XK/qthbbrCos1ZXbr+s=,iv:y6QaBphJpRRIwK61N+O0FuH1invRWmmaL0f5Jx+AgBc=,tag:j3cwz+qjRxURHlsG/3bcVA==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:XiuCcoJheDla,iv:0lZLBCT+Gtx1ZEH++kcLzbDBMBd8+s+j8/OtlZ0cAoQ=,tag:Hf2ghQXFmdJgGxRuaBPlmA==,type:str]
    values.yaml: ENC[AES256_GCM,data:pV5gKqJqgwNAmV4JXWUbfsLxA5oQD/6LsgVQJbTHwY1CHn1ydRewHt279EnMsYs3oD78eZWw56zm28y+JrSgWwJ3uCNtM4xJ8JuS1M9uRjAqHQHfBGgRoc+kaoUbfv69UGBaGBFdEo8gK61WVy/CcIQl6dXPvvyvxiwnU1pXyPHUK4Ro2GxPxP0DVhP7S3eRJHGxBq2BjrqUNAft4NsP,iv:YK5AQuPwrT+CfsrJNOjBPmi6f07nNCwI1QPmiVhjgVw=,tag:v33pyUp5b1Cy6BZP5xZ02g==,type:str]
sops:
    lastmodified: "2026-03-16T04:41:58Z"
    mac: ENC[AES256_GCM,data:wkT8zAeuMoYlA3rJ84RvoG1RGpIU7hdllA+NrwLyNyQ72D69zNTe+bJoYKa2ToBaTKIcJo0RbX2U9i3xHJnwnzk4BP2nqsWHCpr7eCeWAPLLdIi4msk82iBs/nUUdvciEW3DUwPGUHdWsexO6f9WbWoPyNTkhSYUC3sZTqq3y1U=,iv:uxoTVKqouPmvHfdouGYIDS/Nk2qwV3wyvN/Wtv1+Cr0=,tag:pydMWrUAzL8XU4s+YTbKtQ==,type:str]
    pgp:
        - created_at: "2026-03-16T04:41:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQv/X62w3HKpJIObUiCzW8BQ3RSCb0m5X4vCdr56r5pnDf3u
            F2K62njJYz3N8EX1oZ3RI7X0GPpfFUVQQLnDhbQTOzQRRHtxxfHipOwDebHzGrqS
            MhwrMSnLV6MG9fLZ2q/Hl57mWfNnda13VL2UxzeH0eQJt0j3XVZ9NGHBvcMSImLC
            MJ6Wkz8j1kdGDbzySs6TK9f3MajR93spKZEKeTVG4j1xWpDtRals5luiXP1UKOCL
            kgMANY1QQ1po40KkHWBsKeqQwLFwxnw5C4tjverOor9rofN90x1aarKHEaxK7qCi
            bzvR9aOrvJlKTVzyFoO8M7CRYzQwn3uZWtiEJYDh8SQaGff6BjAQP1V1rmrXN3Ua
            r3mTot8xiKrv/XwZQ+Tky+74ysZwnRsiAZK4iZJGwx+CUhWddCNARrl2wN5Xwk+E
            BBjuY+VsdjIJvrzlf1H0t4VPUqlzgzOw//fat+T23uQy1c1bd1Q8+55qQJ9YvJWi
            GDyCqxcjIYPkULnmqmHq0lwB3idT0/rwJqOEpVybLOEscRpQMFE/PmrXswN243M7
            T6MKyUF02s7EWGD6pzKCpOuN29fNMF3WcUouVzYZDRZRrfCFPrLkaCVBfvPAxg1m
            YhH1NswJps/9Wko+wQ==
            =teLx
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
