apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: cloudflare-tunnel-ingress-controller
stringData:
    cloudflaresecret: ENC[AES256_GCM,data:+t4DOvOeK/d9FIQ1DYWmi5z9WI9sD76yt1WeLeAHYeheMp7hDlYDNg==,iv:EDIzBpDOgPYWInAW/MAp4o6KOV9RQ3sHM6MJkLeqpXw=,tag:ZdQJHfmYTeGLBQU+d9gxpg==,type:str]
    cloudflareaccount: ENC[AES256_GCM,data:AkF1ZxsQhZYy6MWteZGXaBkKxD+GCu30YFwW6b//kEY=,iv:PbDnEvmVfog543zYfM9CXJcNVQjDNXFO7uqVpYqT2WM=,tag:XcBCive7NsOHZl0tG4oM2g==,type:str]
    values.yaml: ENC[AES256_GCM,data:m1RKxHGW4zHbut4GkQesktgsHMNBPMIFtofiev3LOx2JACUTPslPkpJcexwA8wGQC4oDpxRAnl3ENhYpFVKUivJTdcRqrzT/bi1jwJHi1gL/ZjphkvBJSkbMt3Uq/Q63A4WlLprqU09kb6oXrp/a6Ht9sK92Oye3XAlZwg==,iv:21+Z+LNLRVUhAz+4RdseDaY3zpPuxaHX4zJu00bmtrA=,tag:YegMLzZaJC1FbAcGZp33Ww==,type:str]
sops:
    lastmodified: "2026-03-16T03:41:53Z"
    mac: ENC[AES256_GCM,data:j7bWrCkgDhqMeYjVxOOIQEP+D8baK0eydmL2i1tsd5ojuX27EI1Jwuc9WpI489afYwkB6Lfq5MKl+J30oN8RmHTyapIzPXWoC6uK9KapW1HZis0skoyUJCAjsa+hlfAczHo5qq9tmIsKXP5qCIQpxw/1nRuKreeYnlK+m7/VFuk=,iv:ZYLqA4xcFoiAyIKjV5HoWq1lJEWGoltuhtXOj0yqAsE=,tag:jb+MjbywvGuUE3G3Dd79XA==,type:str]
    pgp:
        - created_at: "2026-03-16T03:41:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQwAsI6vkzDsGcMqhiCsGipaxdPH0JQGYwIQrPw2bWtigfri
            /cCBq4DfRwC4Ag2zxDCQcpWwSyAlUck+38J4i2gHxqaQO5rvYGGV7GcTGCSK6Ljc
            +TzMrz8euLEwy1J9MaVqzx8D+8oMdJZpOoXv7nGOs9Ja8cpOg7WE4kHqB9ZUozMN
            xRB2AMhJxrtKC74Of0592QNyd+cH5N1qupbrpOgrNbnH0VWVqeVQWGGlcm8wANUd
            jMTuJDPGUm5l/2JgQRqmBsKHZ79PXGuBmA2v0RZCqjUdqNseINmZpoO+uomHb/3c
            zploj85Z0D9x4lVllkyFz83W/wNzEzhMt7ELK4LXrPQFyCVhniWAHTswO5cbYP1N
            iL6hi7TiiNXdWkoMcC1l5YJjevP9J0TsUA9alwRqUCJyKXPlLU8mlLQt871CBCUc
            uVnIhsnPkactEs2WRN9RTuLfvcPxKRrDjAhb52FJFHtngb7vFpf8IF9ic0ezMT6S
            AAXnAK4OGEWYVh9DvnrH0lwBGOUElB2fjveQL92hnFiNWOeOUwoa1H9tccG4XE3d
            iabBl1Iub0a+e83vxqX3JCByYGsfAtgsVDeXXfMunUXc3p2Oe4f9Pt5hG6Y69bVT
            4F9o8wwn4cYJnfLDkw==
            =QgXF
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
