apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: cloudflare-tunnel-ingress-controller
type: Opaque
stringData:
    api-token: itSGwymwLaNDk_L_Jdb6VE8ynzcWdzXT2243g131
    cloudflare-account-id: 85dfa5d3c083a5bc0b569603e781206c
    cloudflare-tunnel-name: tunelcito
    values.yaml: |
      cloudflare:
        api-token: itSGwymwLaNDk_L_Jdb6VE8ynzcWdzXT2243g131
        cloudflare-account-id: 85dfa5d3c083a5bc0b569603e781206c
        cloudflare-tunnel-name: tunelcito