---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-access
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.wololoaeyoyo.com"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: external-secrets