apiVersion: v1
kind: Secret
metadata:
    name: vault-token
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:k59B3jegoaILilP/3KKDye89UOxzdLAUrE3bwA==,iv:rGorEmwro7a3akqhiDDmL0T7UqC9eeKrfzzWByO+YwI=,tag:9c5CSLRM3E2+zx/46i/aAg==,type:str]
sops:
    lastmodified: "2026-03-16T21:25:00Z"
    mac: ENC[AES256_GCM,data:/uVl/XutgHNpEdXDBBm0HaEPgXckgl0/oa52/L1Xn1u9kRf32V/xr4+Ku2pEJj3IwP/vkNMkOhcr58M4Rskl8NxYZ5h1EEBaJ8E2nMxC2C64UXULSwNI+6Z/vwYB5drb4THSX7My0btlNxG6ylfPJVea4KKWU5dKEtmK7ejJRgI=,iv:mJRVIDZYaFJMUzrNAbGFRxHdxfhIpIjQF0D6870cbx8=,tag:gqKIGtxeyq2ACjq4q+ou6w==,type:str]
    pgp:
        - created_at: "2026-03-16T21:25:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQv/dV5TyosmIw/BalCeGm7SBgG7ME36bUvSMyeKAHOxCjHb
            kSwPQxhDAUBcUqxRqIqygzwiWzH/A2VrSiED+48fT4tUXqhpuj3QwXPQtXx+9rM6
            53sKpYKKzWmbWOFha0oq9ms25ZXPgMJ7IKDoSi90v0TEZm4Aug3yTJObGsoDlpwy
            mJNFwLH1TkEdXh2b2vTaH+F+Ly2EE03rR/67iRN82KEXemSNJFAJAl7Yxj2G5bJL
            405KfqPk9wI22F2tlCiR0tzFU+BKBB4Rc54b4dpyq5UBfRzG1wHH6qft95H6DRJJ
            7FrVXDRKPEr2+Q1RlCcgbEMpo5/kbjriEuCNO4ec0xYRhWf40Kf87d53A1Gp4hFG
            fu9fXoiY292Y43datFYWmFV3oGOukSzIMPM/h6918Y9q7nUsCYJmCRyT1kqEHdph
            EfwbGUY4yXhaJ6V1az9FjJqDO2KqTeelucrvVFuUZ8NFdNoyCPhXsJLdhTAmZaUX
            4y3g5t4OVF9SWCxbVfoH0l4BP/xpaACJWlOgLMGMIvypCr8k63Wa36v2Ky+j9RSV
            0dtrGwlxttReeX+l5IWYu2dSpUNQfLHVcKfnhZxE/M5AxapuDliIuBppeoP4QIUZ
            9F64wTS6a7hYRJPDP1Gu
            =zYOl
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
