apiVersion: v1
kind: Secret
metadata:
    name: vault-token
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:YYx65vKfsPNgNRZL4Tv0nKqRHxgSmeHVGw5KWg==,iv:1F49sh3PVmU1ipEpNykn9+ULHxFO3+YKiAWEd7I12dY=,tag:mte1QfUdbaK2GXBIn2Abpw==,type:str]
sops:
    lastmodified: "2026-03-17T04:39:07Z"
    mac: ENC[AES256_GCM,data:tZCYHze5KV96AFkgy561Xf7abjmPdz8YlFIZPX8FLOREV+0qa079l6Iw0ZB0dzg9FdqWsqSE19UEKyXNyxOmfKxXXspU1Xe5z+eBqiJfvlqWF2tdD5WGgWZ/KkqBq4uf6YY3vfKyuKxOYc0mp3F0teb8FqropDUUWxXkT/mlch4=,iv:QyS/dmQftriGiKDPFY8rEtZgjz8948hIyneFlfmRy3Q=,tag:ZxPRsZGd36LZlbAE7zklOw==,type:str]
    pgp:
        - created_at: "2026-03-17T04:39:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3jb8FDLAxZBAQwApgv8b3Ib+CMdkFtQ8r/iZn2yczCvNPNuvg5/XMJCE+aM
            BP4T6gAnMRbLhXAf/uxgC5oRVarxQN1V2FEsfyUiB6awAiThBGHF0LXPrnAJDjPR
            KM+WM+x7R5XQnVHD7dBhU/GsmIvSImw8cRQvQFMlAQUPY4kPgkYqoep2hM+r9p4A
            mBVe6ejXBjla+VbtVLjiVzjifEH0Mj4I9hobhFB6ElpHRRRBUWxR1SmlXurEa/bQ
            ZfU1QQrte9y3ka04nDvCT7Msdh0IOTitFAbyK2Cko5aibZsWyHmcBlFugnCh54Vz
            Xzh2Htnoj8Dnl8a9CuO03dgDfBFF5zqgmwmTTG2o7T3DnV4jK9HDR93ny4lB9Lcj
            dAxtzECG5QpKL05z5eMXDKAJR29C9Wqf73ecpr9J+WQzkKWX/mOawPSfiguAhkPG
            O6xaFuiKvS0IqJ0ALCOtMIRVNyT8djppd4EQyi0ehMoPcxBt3oCRIgHcPATchZbN
            FG0Tum36f6LnIBopbcwA0l4BrPGREXrx+vf+gO22M+cejtiG+PFHj9TVne7w+n/5
            mZ7RUp95zHPyrhZUECUk/Q5TRmKhQWRnKx4zmovTe+NoS2xHBOD8g2cFkObYAY35
            rCCeJpdfPQKorl/8YkVk
            =K6Tr
            -----END PGP MESSAGE-----
          fp: 16CF812FC89789B4EEAA733C61680D932EDF98A7
    encrypted_regex: ^(data|stringData|secret|secureJsonData)$
    version: 3.12.1
