apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: USERADMIN
      remoteRef:
        key: lgtm/data/grafana
        property: data.USERADMIN
    - secretKey: PASS
      remoteRef:
        key: lgtm/data/grafana
        property: data.PASS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-datasource-secret
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: github-datasource-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: lgtm/data/grafana
        property: data.GITHUB_TOKEN
---



