apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: userKey
      remoteRef:
        key: lgtm/data/grafana
        property: data.USERADMIN
    - secretKey: passwordKey
      remoteRef:
        key: lgtm/data/grafana
        property: data.PASS




