apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-deployment
  namespace: grafana
spec:
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
      version: 9.2.10
  interval: 1m0s
  values:
    replicaCount: 1
    plugins:
    - grafana-github-datasource
    persistence:
      type: pvc
      enabled: true
      storageClassName: longhorn
      accessModes:
      - ReadWriteOnce
    size: 1Gi
