apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-readme-stats
  namespace: github-readme-stats
  labels:
    app: github-readme-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-readme-stats
  template:
    metadata:
      labels:
        app: github-readme-stats
    spec:
      containers:
        - name: github-readme-stats
          image: wololoaeyoyo/github-readme-stats:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PAT_1
              valueFrom:
                secretKeyRef:
                  name: github-readme-stats-secret
                  key: PAT_1
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
