apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-readme-stats-secret
  namespace: github-readme-stats
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: github-readme-stats-secret
    creationPolicy: Owner
  data:
    - secretKey: PAT_1
      remoteRef:
        key: github-readme-stats/data/PAT_1
        property: data.PAT_1
