apiVersion: v1
kind: ConfigMap
metadata:
  name: zomboid-configmap
  namespace: zomboid
data:
  values.yaml: |
    image:
      tag: v1.1.1
    service:
      type: ClusterIP
    resources:
      requests:
        memory: 5Gi
        cpu: 1.5
      limits:
        memory: 6Gi
        cpu: 3.0
    volumes:
      serverPVC:
        size: 25Gi
      dataPVC:
        size: 25Gi
      storageClassName: longhorn
    config:
      serverName: "Merwebo Zomboid"
      # mapNames: "Muldraugh, KY"
      maxMemory: "4g"
      maxPlayers: "16"
      pvp: "true"
      public: "false"
      pauseEmpty: "true"
      autosaveInterval: 15
      backupsCount: 5
      backupsPeriod: 120
      adminUsername: "wololoaeyoyo"
      steamVAC: "true"
      antiCheatType21: "true"
      # True Music, Common Sense, Better Sorting
      # modIDs: "2613146550;2875848298;2313387159"
      #modNames: "truemusic;BB_CommonSense;BetterSortCC"
