apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: zomboid-binding
  namespace: zomboid
subjects:
- name: zomboid-dedicated-server-service
  spec:
    protocol: udp
    fqdn: zomboid.merwebo.org
    target: udp://zomboid-dedicated-server-service.zomboid.svc:16261
    proxyPort: 16261
- name: zomboid-dedicated-server-service
  spec:
    protocol: udp
    fqdn: zomboidconnect.merwebo.org
    target: udp://zomboid-dedicated-server-service.zomboid.svc:16262
    proxyPort: 16262
tunnelRef:
  kind: ClusterTunnel
  name: tunnel-cluster-mer
