#source https://grafana.com/docs/tempo/latest/collect/logs-in-kubernetes/
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-configmap
  namespace: minecraft
data:
  values.yaml: |
    minecraftServer:
      eula: "true"
      version: LATEST
      gameMode: survival
      motd: "Mariguanos y periqueros!!"
      onlineMode: true
      memory: 4g
      servicePort: 25566
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 6
    persistence:
      annotations: {}
      dataDir:
        enabled: true
        Size: 6Gi
    initContainers:
      - name: mmproxy-init
        image: busybox
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["/bin/sh", "-c"]
        args:
          - |
            ip rule add from 127.0.0.1/8 iif lo table 123
            ip route add local 0.0.0.0/0 dev lo table 123
            ip -6 rule add from ::1/128 iif lo table 123
            ip -6 route add local ::/0 dev lo table 123
    sidecarContainers:
      - name: go-mmproxy
        image: ghcr.io/path-network/go-mmproxy:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        args:
          - "-l"
          - "0.0.0.0:25565"
          - "-4"
          - "127.0.0.1:25566"
          - "-6"
          - "[::1]:25566"
          - "-p"
          - "tcp"
          - "-v"
          - "2"