apiVersion: networking.cfargotunnel.com/v1alpha1  
kind: TunnelBinding  
metadata:  
  name: minecraft-binding  
  namespace: default  
subjects:
- name: minecraft-minecraft-deployment
  spec:
    protocol: tcp
    fqdn: minecrack.merwebo.org
tunnelRef:
  kind: ClusterTunnel
  name: tunnel-cluster-mer