apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - name: http
      protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
