apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: mimir
spec:
  targetNamespace: mimir 
  chart:
    spec:
      chart: mimir
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 6.0.5

  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: mimir-configmap