apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: mimir
spec:
  targetNamespace: mimir 
  chart:
    spec:
      chart: mimir-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 6.1.0-weekly.376

  interval: 1m0s
  values:
    containerEnvVars:
      KAFKA_LOG_RETENTION_HOURS: 1
      ACCESS_KEY: 
        valueFrom:
          secretKeyRef:
            name: mimir-secret
            key: ACCESS_KEY
      SECRET_KEY: 
        valueFrom:
          secretKeyRef:
            name: mimir-secret
            key: SECRET_KEY
  valuesFrom:
    - kind: ConfigMap
      name: mimir-configmap
      valuesKey: values.yaml