apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chibi-safe-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./chibi-safe
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
---