apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-ingress-controller-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./cloudflare
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
---