apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: discord-default
  namespace: flux-system
spec:
  interval: 1m
  path: ./bot-discord
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
