apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./external-secrets/release
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-store
  namespace: flux-system
spec:
  interval: 15m
  dependsOn: 
  - name: external-secrets-system
  path: ./external-secrets/clusterSecret
  prune: true # remove any elements later removed from the above path
  timeout: 2m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
