apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n-default
  namespace: flux-system
spec:
  interval: 1m
  path: ./n8n
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: n8n
      namespace: default
