# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: nginx--default
#   namespace: flux-system
# spec:
#   interval: 1m
#   path: ./nginx
#   prune: true
#   timeout: 2m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   healthChecks:
#     - apiVersion: apps/v1
#       kind: Deployment
#       name: nginx
#       namespace: default
