apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yt-dlp-backend
  namespace: flux-system
spec:
  interval: 1m
  path: ./yt-dlp-backend
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: yt-dlp-backend
      namespace: yt-dlp-backend
