apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-secret
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: claude-secret
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY
      remoteRef:
        key: clause/data/api
        property: data.ANTHROPIC_API_KEY





