apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-api-keys
  namespace: openclaw
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: openclaw-api-keys
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: clause/data/api
        property: data.ANTHROPIC_API_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: clause/data/api
        property: data.OPENAI_API_KEY
    - secretKey: OLLAMA_API_KEY
      remoteRef:
        key: clause/data/api
        property: data.OLLAMA_API_KEY



